### PR TITLE
Allow shortening of zero addresses and addresses with zero-bytes prefixes

### PR DESCRIPTION
**Pull request by k06a**

### CODE REVIEW

**Comment by nickscavuzzo33** [comment]
ever upated here ?

**Review by web3security — CHANGES_REQUESTED** [review]
All bytes (included addresses) encoded as RLP should strictly follow the standard which is having 1 byte as prefix of the data to deserialize it so in case of EVM compatible addresses it should always have a minimum of 21 bytes (1 byte prefix + 20 bytes for an address)as memory pointer will point to the prefix byte.

More info: https://ethereum.org/en/developers/docs/data-structures-and-encoding/rlp/

In case I misunderstood something can you please elaborate more on the reasons for this PR to use "short-addresses"? A short-address attack can likely be triggered by using this IMHO, thanks.

**Comment by wschwab** [comment]
@k06a feel free to reach out if you think the security comment above is in error (we should see if you reopen, and should have normal lead times - you shouldn't need to wait 6 months for a response now), though I'm closing for now

**Comment by k06a** [comment]
@web3security I don’t see any specification on how addresses should be rlp-encoded. Some software could do this differently for addresses with leading zeroes.

**Comment by web3security** [comment]
Hi @k06a, it is true that it does not mention addresses case explicitly but it does with "< 55 bytes" encoding where addresses are and basically there is no way to have "zero-bytes prefixed" in our network.

Considering that the PR was proposed for both "shortening" and "zero-bytes prefixed" (per title), the later is not valid.

We understand that "shortening" is then your proposal however being the function some kind of a "library" function, it might be opening side effects as stated above so in our opinion there is no enough reasoning behind to expose this to uncertain risks to just save few bytes in very few cases. 

Last but not least, it is also true that some software could do it differently (which btw is prune to human error) we prefer however to follow standards, so despite above RLP reference does not mention explicitly how to handle addresses, it basically means for us that addresses should be handled as standard Ethereum 20-bytes addresses.

I hope this helps.

**Pull request closed without merging**
