### PR TITLE
Add ChainSecurity audit

### PR DESCRIPTION
**Pull request by gretzke**

### CODE REVIEW

**Comment by wschwab** [comment]
@cvhpoly can you take a look at this?

**Comment by wschwab** [comment]
also, @gretzke could we get a link to the audit in the README (just like the link to the Halborn audit that's there already)

**Review by wschwab — APPROVED** [review]

**Comment by cvhpoly** [comment]
@wschwab can you add Devashish (@dev1644) here so he can be one of the reviewers?

**Review by 0xCVH — APPROVED** [review]

**Review by 0xCVH — APPROVED** [review]
approved!

**Review by 0xCVH — APPROVED** [review]

**Comment by 0xCVH** [comment]
@wschwab I don't have write access so my approval is not valid...

**Review by QEDK — APPROVED** [review]

**Pull request merged**
